export const FETCH_USERS_REQUSET = "FETCH_USERS_REQUSET"
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE"

export const FETCH_POSTS_REQUSET = "FETCH_POSTS_REQUSET"
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS"
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE"